### ISSUE TITLE
Update discord link

### ISSUE THREAD

**Issue by jycouet** [techniq/svelte-ux#116]
Just found out about svelte-ux, looks great.
It seems that tour discord links are outdated, maybe you could refresh them?
Thx

**Comment by techniq** [comment]
Thanks!  Not sure why the link broke. I'm currently AFK and having trouble updating on my phone. I think the server ID is now cKChJ4R6. Not sure why it changed, or when. Could you send a PR by chance?

**Comment by techniq** [comment]
@jycouet [Fixed](https://github.com/techniq/svelte-ux/commit/40331b68315ed3a4ea39b2003902f2cd4fa4e959).  Thanks for the report.  Not sure what caused it to change
