### ISSUE TITLE
[SelectField] Standardize with MenuField / general improvements

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#132]
Extracted from PR #130

- [x] Use same [Options](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/MenuField.svelte#L15) type instead of [any](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/SelectField.svelte#L25)
  - Will use `label` instead of `name` by default (can still be overwritten by `optionText()`, maybe we call this `optionLabel()`, or maybe we require the data to be processed ahead of time and remove this and `optionValue()`
- [ ] Pass `icon` prop to [MenuItem](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/SelectField.svelte#L447-L461) like [MenuField](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/MenuField.svelte#L130)
- [x] Should we update the `<SelectField icon={...} />` based on the selected `<MenuItem icon={...} />`?
  - Add a prop to opt-in to this functionality (`activeOptionIcon` or something)
  - Require the user to do this (like the SelectField [example](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/routes/docs/components/SelectField/+page.svelte#L175) currently does.
- [x] Fix clicking on Chevon icon/button to close (re-toggles open) (#93)

**Comment by techniq** [comment]
The first task is also in the [Road to v1](#59) issue

**Comment by techniq** [comment]
Task 1 and 3 resolved via https://github.com/techniq/svelte-ux/pull/127.

**Comment by techniq** [comment]
@willnationsdev Tagging you here if you're interested in knocking out these, but don't feel like you have to.

**Comment by willnationsdev** [comment]
Got a PR, but even with the icons added back in, the blue coloration they had before on the docs page is now gone. I'd bet there're styles somewhere in the docs that need to be adjusted. Cause you wouldn't wanna make a change like that to the component itself or to the theme that applies to everyone's usage of the SelectField's MenuItems - you just want the docs page. But the docs page didn't appear to have Tailwind classes is was merging in via attributes, so idk where those styles came from.
