### ISSUE TITLE
Svelte 5 compatibility

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#144]
Issue to track any Svelte 5 compatibility issues.  Hoping close to `0` changes are required in Svelte UX to support 5.

---
## ⚠️ PENDING: sveld (API docs) not compatible
issue: #435 

---
## ✅ FIXED: `MultiSelect` hangs browser (MultiSelectField / MultiSelectMenu appear to work fine)
example: https://svelte5-docs.svelte-ux.pages.dev/docs/components/MultiSelect (see [screenshot](https://github.com/techniq/svelte-ux/issues/144#issuecomment-2261124165))
fix: https://github.com/techniq/svelte-ux/issues/507

---

## ✅ FIXED: `SelectField` raises `node_invalid_placement_ssr`
Server-side
> node_invalid_placement_ssr: `<button>` (src/lib/components/SelectField.svelte:415:0) cannot contain `<button>` (src/lib/components/Button.svelte:446:0)
>
> This can cause content to shift around as the browser repairs the HTML, and will likely result in a `hydration_mismatch` warning.

Client-side
> Uncaught (in promise) HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

fix: https://github.com/techniq/svelte-ux/pull/436/commits/4e172184edd336e445f4265331efc0abb7530d7d

---
## ✅ FIXED: `Form` `$: dispatch('change', ...)` called immediately (not after change)
examples: [svelte 4](https://svelte.dev/repl/992a3d0077af44819191534599ca7966?version=4.2.18), [svelte 5](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE5WQQWuEMBCF_8owFFxBtOdUF0rbX1F7CHHcDcQkJKNQJP-9ZFe0tL30MId5ee8xX1YctaGI4n1FKydCgc_eY4X86fMSFzJMWGF0c1BZaaMK2vO5tz3rybvA8OIm7yxZhjG4CYq62ZX6XlA89bZtjqRtj4yzQl2lvVC3EnRnUM5GZ6g27nIq7i9FBVQPxFKbMkFza8AKJzfoUdOAgsNMqdoR9vJ_gqygAkmmt4Usv-roJasrBUgb2AGTQ_lQhmGzQfd3-FRmOxtiWKSZCTp4vCl5HsSe_8a6bs5U_vy239Af6QupmNI8wwEAAA==)
fix: https://github.com/techniq/svelte-ux/commit/f419435edbf4f0c004896e87e92b9f7ba770bcc9

---
## ✅ FIXED: `SelectField` selection not working (bind:value issue?)
example: https://svelte5-docs.svelte-ux.pages.dev/docs/components/SelectField
fix: https://github.com/techniq/svelte-ux/pull/448

---
## ✅ FIXED: `Duration` Cannot access 'timer' before initialization
example: https://svelte5-docs.svelte-ux.pages.dev/docs/components/Duration
fix: https://github.com/techniq/svelte-ux/pull/447

---
## ✅ WORKAROUND: `Dialog`/`Drawer` can only be opened once (likely portal related).  Removes subsequent elements.  Issue with portal'd content and multiple elements in same 
issue: https://github.com/sveltejs/svelte/issues/12440, see also: https://github.com/sveltejs/svelte/issues/12427#issuecomment-2226916099
example: https://svelte5-docs.svelte-ux.pages.dev/docs/components/Dialog
workaround: Place each portal'd content into separate `{#if}` block ([commit](https://github.com/techniq/svelte-ux/commit/54d9d39ee7bdb712f6c2e85faea1701aae9fe3ba))

---
## ✅ WORKAROUND: Portal actions timing is different with available DOM
issue: https://github.com/techniq/svelte-ux/issues/437
fix: add explicit `document.body` for example, likely only affects docs (presence of `.PortalTarget` element)

## ✅ WONTFIX: `<tr>` is invalid inside `<table>`
issue: https://github.com/sveltejs/svelte/issues/12090
fix: add explilcit `<tbody>`

---
## ✅ FIXED: <slot> can only receive attributes, not directives
issue: https://github.com/sveltejs/svelte/issues/10382
fix: https://github.com/sveltejs/svelte/pull/10391

---
## ✅ FIXED: `type` attribute must be a static text value if input uses two-way binding
Fixed via: https://github.com/sveltejs/svelte/pull/9713
Reported in [discord](https://discord.com/channels/920755200552226868/1168230830271893626/1178249611845062716).  If ran within the Svelte 5 beta (ex. `5.0.0-next.15`), currently [Input](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Input.svelte) throws a `'type' attribute must be a static text value if input uses two-way binding` error

![image](https://github.com/techniq/svelte-ux/assets/177476/3362d9c0-319a-4c39-ae34-84543292028e)

---
## ✅ FIXED: `let` directive on `<svelte:self>`
issue: https://github.com/sveltejs/svelte/issues/9710
fix: https://github.com/sveltejs/svelte/pull/9727

**Comment by techniq** [comment]
Thanks @CropWatchDevelopment, but it looks like this is a regression with the Svelte 5 compiler (see [issue](https://github.com/sveltejs/svelte/issues/9709) and Twitter/X [discussion](https://twitter.com/techniq35/status/1729936047599939584), including [confirmation](https://twitter.com/dummdidumm_/status/1729956838622273683) by Simon (Svelte/Vercel team).

I also found a [workaround](https://twitter.com/techniq35/status/1729936547414265922) using `<svelte:element>`, although I would prefer to wait for it to be fixed upstream (which it should be).  It looks like Svelte 3/4 had an explicit [check](https://github.com/sveltejs/svelte/blob/d15bc822e0f8fecd87c84f2bdd3ac63f3e2e33cc/packages/svelte/src/compiler/compile/nodes/Element.js#L1240) for `bind:this` that likely was overlooked as part of the Svelte 5 rewrite, so likely the fix will be similar (and hopefully as simple).

Would it be OK if we wait a bit to see if this is resolved upstream before we consider a workaround?

I'm curious what you found in [TreeList](https://github.com/techniq/svelte-ux/blob/f5ed56fcf8ffb196b1a88a8e087642a2e698d36c/packages/svelte-ux/src/lib/components/TreeList.svelte).

**Comment by CropWatchDevelopment** [comment]
100% Yes OK to wait until later. After checking the Svelte repo and seeing all of the v5 issues logged. I am thinking I may wait a few months even before making the move. It seems like v5 may take a bit be fully worked out :) I will pull down the PR, but Hope to help out in the future!

**Comment by techniq** [comment]
> 100% Yes OK to wait until later. After checking the Svelte repo and seeing all of the v5 issues logged. I am thinking I may wait a few months even before making the move. It seems like v5 may take a bit be fully worked out :) I will pull down the PR, but Hope to help out in the future!

FWIW, the `bind:this` issue is already [fixed](https://github.com/sveltejs/svelte/pull/9713) and should be on `5.0.0-next.16` once released (already on the preview REPL).  I was going to test my StackBlitz until I realize .16 wasn't published yet.

TBH, that's my plan ATM.  As much as I love all the great things coming in Svelte 5, I personally will wait closer to the official release before I focus too much on it.  My plan is for Svelte UX (and LayerChart) 1.0 releases to be fully compatibility with Svelte 3/4/5, and 2.0 I'll probably start embracing some of the Svelte 5 features (runes, snippets, etc) which will likely break 3/4 compatibility, but as long as 5 is a drop in replacement for 3/4, I think that's a fair tradeoff.

Just the speed/size improvements in 5 running non-rune mode is exciting.

Thanks for the PR and discussion.

**Comment by dimfeld** [comment]
Filed https://github.com/sveltejs/svelte/issues/10382 because SelectField.svelte fails to compile with latest Svelte 5.

![CleanShot 2024-02-02 at 20 42 27](https://github.com/techniq/svelte-ux/assets/1369558/5a102ce7-f222-41a7-b7de-e5133435250c)

**Comment by techniq** [comment]
Thanks @dimfeld for submitting the upstream issue with repo.  I've updated this issue's description to make it easy to track any known Svelte 5 compatibility issues.  The Svelte team has been amazingly fast resolving these thus far.

**Comment by dimfeld** [comment]
Haven't tried it but I think this will hit svelte-ux as well https://github.com/sveltejs/svelte/pull/10395

**Comment by techniq** [comment]
Identified the root cause of the Dialog/Drawer problem (portal'd content with elements in the same conditional) - https://github.com/sveltejs/svelte/issues/12440

**Comment by techniq** [comment]
Workaround identified - https://github.com/techniq/svelte-ux/commit/54d9d39ee7bdb712f6c2e85faea1701aae9fe3ba

**Comment by dimfeld** [comment]
The `SelectField` bug is quite strange... The option setting code gets called a bunch of times, not sure if that's normal or not. But at some point updateSelected is called from the reactive statement, and `options` is an empty array instead of the actual options. That's why things get cleared.

**Comment by dimfeld** [comment]
Oh actually I figured it out... The problem is the `SelectField` that is using `optionsAsync`, which starts out empty. So at some point when that SelectField runs its reactivity it clears the value since its options don't contain the number, which then propagates back to the first SelectField.

Commenting out the example with `optionsAsync` makes everything work fine.

I think this is actually a case where some of the weird cross-component reactivity problems in Svelte 4 are fixed, and the "correct" behavior is only correct because Svelte 4 was losing the reactivity chain at some point. So here we just need to not `bind:value` on the optionsAsync SelectField, or perhaps bind to a different value variable.

**Comment by dimfeld** [comment]
`Duration` problem is because getDelay tries to access `$timer` but it's also called before `timer` is actually created, in the initial call to `timerStore`. 

This fixes it although it's a big hack. There's probably a better way to write this but the standard tricks like `typeof timer === 'undefined'` didn't work.

```diff
<script lang="ts">
  function getDelay() {
+   const endTime = end ?? (initialized ? $timer : null);
+   const newDuration = getDuration(start, endTime, duration);
-   const newDuration = getDuration(start, end ?? $timer, duration);

    const unitsMoreThanSeconds = [
      newDuration?.years,
      newDuration?.days,
      newDuration?.hours,
      newDuration?.minutes,
    ].filter((x) => x).length;

    // DurationUnits is indexed biggest (Year) to smallest (Milliseconds)
    if (minUnits < DurationUnits.Second) {
      // Never showing seconds, so only update once a minute
      return 60 * 1000;
    } else if (unitsMoreThanSeconds >= totalUnits) {
      // If only showing values above seconds, only update once a minute (could update even less frequently for hours, etc)
      return 60 * 1000;
    } else {
      return 1000;
    }
  }

+  let initialized = false;
  const timer = timerStore({
    delay: getDelay(),
    disabled: end != null,
    onTick: () => {
      // Update delay based on display duration
      const newDelay = getDelay();
      if (newDelay != timer.getDelay()) {
        timer.setDelay(newDelay);
      }
    },
  });
+  initialized = true;

  $: displayDuration = humanizeDuration({
    start,
    end: end ?? $timer,
    duration,
    minUnits,
    totalUnits,
    variant,
  });
</script>

<span class={cls('Duration', settingsClasses.root, className)}>{displayDuration}</span>
```

**Comment by dimfeld** [comment]
MultiSelect issues are related to `mode = "Immediate"`. I haven't debugged further yet.

**Comment by techniq** [comment]
Just spotted another Svelte 5 regression with `SelectField` while looking at the [docs](https://svelte5-docs.svelte-ux.pages.dev/docs/components/SelectField).  Sometimes (but not always) there is an extra empty option at the top.

![image](https://github.com/user-attachments/assets/3ee5ea91-10a6-4bba-90b0-d995fc91ce48)

**Comment by techniq** [comment]
Did a quick investigation and it looks to go aways unless you add the "`append` slot (field actions)" example (along with basic).  Having only those 2 examples causes the issue).  Probably because the Form on:change is being called more than expected.

```svelte
<h2>`append` slot (field actions)</h2>

<Preview>
  <Toggle let:on={open} let:toggle let:toggleOff>
    <SelectField {options}>
      <span slot="append" on:click|stopPropagation role="none">
        <Button icon={mdiPlus} class="text-surface-content/50 p-2" on:click={toggle} />
      </span>
    </SelectField>
    <Form
      initial={newOption()}
      on:change={(e) => {
        options = [e.detail, ...options];
      }}
      let:draft
      let:commit
      let:revert
    >
      <Dialog {open} on:close={toggleOff}>
        <div slot="title">Create new option</div>
        <div class="px-6 py-3 w-96 grid gap-2">
          <TextField
            label="Label"
            value={draft.label}
            on:change={(e) => {
              draft.label = e.detail.value;
            }}
            autofocus
          />
          <TextField
            label="Value"
            value={draft.value}
            on:change={(e) => {
              draft.value = e.detail.value;
            }}
          />
        </div>
        <div slot="actions">
          <Button on:click={() => commit()} color="primary">Add option</Button>
          <Button on:click={() => revert()}>Cancel</Button>
        </div>
      </Dialog>
    </Form>
  </Toggle>
</Preview>
```

Definitely more to look into, but this helps to reduce it down.

**Comment by techniq** [comment]
So the root issue of the extra SelectField option being added is because `<Form on:change={...}>` is dispatched immediately in Svelte 5.

This is because the reactive dispatch in [Form](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Form.svelte#L21) is called immediately in Svelte 5 ([REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE5WQQWuEMBCF_8owFFxBtOdUF0rbX1F7CHHcDcQkJKNQJP-9ZFe0tL30MId5ee8xX1YctaGI4n1FKydCgc_eY4X86fMSFzJMWGF0c1BZaaMK2vO5tz3rybvA8OIm7yxZhjG4CYq62ZX6XlA89bZtjqRtj4yzQl2lvVC3EnRnUM5GZ6g27nIq7i9FBVQPxFKbMkFza8AKJzfoUdOAgsNMqdoR9vJ_gqygAkmmt4Usv-roJasrBUgb2AGTQ_lQhmGzQfd3-FRmOxtiWKSZCTp4vCl5HsSe_8a6bs5U_vy239Af6QupmNI8wwEAAA==)) but not in Svelte 4 ([REPL](https://svelte.dev/repl/992a3d0077af44819191534599ca7966?version=4.2.18)).

`Component.svelte`
```svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();
  let value = 0;	
  
  $: dispatch('change', { value });
</script>
```

`App.svelte`
```svelte
<script>
  import Component from './Component.svelte';
</script>

<Component on:change={e => console.log('change', e.detail)} />
```

I'm debating on whether this is a reportable regression, or works as expected (`$: console.log(value)` runs immediately in Svelte 4, just not `$: dispatch(value)`).

If not, I need to come up with a solution to wait for the value to change.  I initially thought of...

```svelte
<script>
  //...

  let isMounted = false;
  onMount(() => {
    isMounted = true;
  });

  $: if (isMounted) {
    dispatch('change', $_state);
  }
</script>
```
...but then `isMounted` is updated reactively, which fires the change event.

@dimfeld thoughts?

**Comment by techniq** [comment]
One workaround is to use a `changeStore` since the form state is a store in this case.

```js
$: dispatch('change', $_state);
```
becomes...

```js
const changed = changeStore(_state, (value) => dispatch('change', value.current));
$changed; // must subscribe to store to get onChange callbacks
```

**Comment by techniq** [comment]
@dimfeld I decided to go ahead and [use](https://github.com/techniq/svelte-ux/commit/f419435edbf4f0c004896e87e92b9f7ba770bcc9) the `changeStore` fix/workaround.  Still curious your thoughts if this change is work a report.

**Comment by dimfeld** [comment]
It sounds more like a bug that it *wasn't* doing this in Svelte 4 :) And actually this is https://github.com/sveltejs/svelte/issues/4470 

Yeah anything that suppresses that first firing seems fine.

**Comment by iniznet** [comment]
Using SelectField outside a dialog gives me the following warning in svelte@5.0.0-next.260. I'm not sure what's causing this, but the select field still seems to work fine.

```
(index):3922 Placing %sveltekit.body% directly inside <body> is not recommended,
as your app may break for users who have certain browser extensions installed.

Consider wrapping it in an element:

<div style="display: contents">
  %sveltekit.body%
</div>
```

But add another select field will break the page as the browser unable to repair broken html, `Uncaught (in promise) HierarchyRequestError: Failed to execute 'appendChild' on 'Node': This node type does not support this method.`

**Comment by techniq** [comment]
@iniznet That's rather interesting, and not sure what would be causing that off the top of my head.  I first thought it might be because of the [portal](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/actions/portal.ts) action, but SelectField/Menu/Popover doesn't use the action (only Dialog/Drawer/Backdrop).

**Comment by techniq** [comment]
Closing this overarching issue as last remaining (known) regression ([MultiSelect](https://github.com/techniq/svelte-ux/issues/507) `mode="immediate"` freezes browser) has been [fixed](https://github.com/techniq/svelte-ux/commit/2524959f59f72ce968624f3235e0b64ba30a88b6).

All that remains is re-adding API docs, which is being tracking in #435 and will be re-added once the library has been migrated to Svelte 5 (planning for EoY).
