### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by GregSharp-app** [techniq/svelte-ux#148]
is there a way to make TextFields support RightToLeft ?

**Comment by techniq** [comment]
Hi @GregSharp-app 👋.  Sorry I don't have any experience with RTL, but I know Tailwind [supports](https://tailwindcss.com/docs/hover-focus-and-other-states#rtl-support) this.  

Leveraging settings/theme, you should be able to apply some class overrides to fit your needs (or some global CSS).  If you recognize something that can be done with the component directly, I'm would review a PR.
