### ISSUE TITLE
SelectField docs page contains form actions that error on submit.

### ISSUE THREAD

**Issue by willnationsdev** [techniq/svelte-ux#152]
While working on your suggestion to incorporate #132 into #127, I came across this bug. After confirming it happened in `main` and not part of my own changes, I'm reporting it here.

If you run `pnpm dev` from the `packages\svelte-ux` directory and navigate to the `SelectField` component's webpage, there are a few parts of the page that contain examples that include `<Form>` usage. When submitting these forms, it now produces a regression in which the following uncaught TypeError is thrown and the UI for said preview example thenceforth freezes until you completely refresh the page to reset things. Not sure when exactly this began happening, but it wasn't an issue a month ago.

```
Uncaught TypeError: Cannot perform 'IsArray' on a proxy that has been revoked
    at clone (<anonymous>:555:19)
    at <anonymous>:555:57
    at Array.map (<anonymous>)
    at clone (<anonymous>:555:48)
    at clone (<anonymous>:562:20)
    at <anonymous>:555:57
    at Array.map (<anonymous>)
    at clone (<anonymous>:555:48)
    at serializeNode (<anonymous>:656:31)
    at Object.remove (<anonymous>:681:15)
```

Investigating the error, it appears to have something to do with the `immer` library and the use of its data outside of the scope in which they are valid. I already tried replacing the use of `draft` in the page's form examples with `current` instead, but that didn't seem to resolve the issue.

**Comment by techniq** [comment]
Thanks @willnationsdev.

I just tried to reproduce myself and it appears to work for me (both on [master](https://svelte-ux.techniq.dev/docs/components/SelectField) and on my local branch I'm working on).

https://github.com/techniq/svelte-ux/assets/177476/d9b4d589-9793-44fe-8830-3bf3689b9690

Am I doing it wrong to reproduce?

Btw, the last time we bumped immer (`10.0.2` => `10.0.3`) was ~[Oct 13th](https://github.com/techniq/svelte-ux/commit/782bc9d4a97d5079173d91f19385715f7f890c45) and the major (`9.0.19` => `10.0.2`) was ~[Sept 13th](https://github.com/techniq/svelte-ux/commit/784c7e72e066ee4b7000213b07683aafcf33123e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R67) when Svelte was bumped from 3 => 4 (which is likely when the regression happened, unless it went unnoticed well before that)

**Comment by willnationsdev** [comment]
Ahhhh, nope, nevermind. Seems that this is being triggered by some sort of Chrome extension I have installed (not sure which one). It worked fine when I ran it in Firefox and Edge.

**Comment by techniq** [comment]
No worries, and I wasn't going to be surprised if it was an immer bug / regression.  I've hit some challenging issues with it (especially with draft scoping).  Hoping to remove it with Svelte 5 runes in the future, hopefully.
