### ISSUE TITLE
Blurry/Pixeleted font on Gooey effect

### ISSUE THREAD

**Issue by MuhammadMehediHasan** [techniq/svelte-ux#159]
![image](https://github.com/techniq/svelte-ux/assets/59830922/62ac2fee-d3ef-4e4f-8045-ad9c396e5285)

**Comment by techniq** [comment]
Hi @MuhammadMehediHasan 👋.  This is mostly related to how the effect works, particularly [<feColorMatrix>](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Gooey.svelte#L35-L43).  You could try adjusting the `alphaPixel` and `alphaShift` to tighten this up, along with maybe tossing a subtle blue to help smooth out the edges.

You might want to look at some of the source material I referenced in #98 (see `Gooey` section) and see if the effect works better there, and what values they used if so.  Lastly, you could try to enable the `composite="atop"` prop to overlay the original value on top, which is what the morphing emoji does.

I don't have much bandwidth ATM to dig much deeper, but if you find a way to improve the example, I would love to update it.

**Comment by MuhammadMehediHasan** [comment]
Thanks
