### ISSUE TITLE
[create-svelte-ux]  - [postcss] Cannot find module 'culori/require'

### ISSUE THREAD

**Issue by mtfwvi** [techniq/svelte-ux#160]
When using [`create-svelte-ux`](https://github.com/techniq/svelte-ux/tree/next/packages/create-svelte-ux), there appears to be some error with the tailwind config `tailwind.cjs` / the module `culori`. This error appears after starting the dev server, without changing the code: 

```
[plugin:vite:css] [postcss] Cannot find module 'culori/require'
Require stack:
- /home/projects/zzmibpamy.github/node_modules/svelte-ux/dist/plugins/tailwind.cjs
/home/projects/zzmibpamy.github/node_modules/svelte-ux/dist/components/Icon.svelte
```

Honestly no idea what causes this issue.

![image](https://github.com/techniq/svelte-ux/assets/72407233/1bca8a54-70dc-444c-b30b-36223eb4ee50)

Try: [Stackblitz](https://stackblitz.com/github/techniq/svelte-ux/tree/main/packages/create-svelte-ux/templates/starter
) [Codesandbox](https://codesandbox.io/p/sandbox/github/techniq/svelte-ux/tree/main/packages/create-svelte-ux/templates/starter
) [SvelteLab](https://www.sveltelab.dev/?provider=github&owner=techniq&repo=svelte-ux&branch=main&path=%2Fpackages%2Fcreate-svelte-ux%2Ftemplates%2Fstarter)

**Comment by jycouet** [comment]
I will have a look asap, it seems strange yes 👀.

**Comment by techniq** [comment]
Hey @mtfwvi , sorry about that.  [culori](https://github.com/techniq/svelte-ux/pull/146/files#diff-b0b16ebacdbfa403a58014b6e05af052f242c38fc17e3910dd6fe66af4848871R2) is used in the theme [PR](https://github.com/techniq/svelte-ux/pull/146/) and I thought I had properly isolated it using the `next` tag, but appears to be getting picked up here.  My guess is the [latest](https://github.com/techniq/svelte-ux/blob/main/packages/create-svelte-ux/templates/starter/package.json#L35) version in the `package.json` of the template is grabbing the `next` version.

**Comment by techniq** [comment]
Actually I see now... it appears when I published the last few `next` versions manually (`npm publish`) I accidently pushed them to `latest` and not `next`.

![image](https://github.com/techniq/svelte-ux/assets/177476/08c220de-5bdd-430c-a14b-eb60d8169ac9)

As a workaround, you should be able to manually change your `svelte-ux` version to `^0.57.1` in your package.json.  I'll work on fixing the published `latest` today as well.  Sorry about that.

**Comment by techniq** [comment]
OK, `latest` should be fixed.  
![image](https://github.com/techniq/svelte-ux/assets/177476/68c6f8cb-94aa-4f3b-aa1c-ac5f7565a4dd)
