### ISSUE TITLE
[TextField] Can not enter decimal separator (Safari)

### ISSUE THREAD

**Issue by pekeler** [techniq/svelte-ux#163]
When entering a `.` or `,` as in `12.34`, the value gets deleted.

**Comment by pekeler** [comment]
(This is in Safari 17.1, seems to work fine in Chrome)

**Comment by techniq** [comment]
Thanks for the report @pekeler.  Yeah, it appears to only affect Safari (also tested Firefox).  

My first thought was how Safari might he handling `Number('12.')` but it looks consistent with Chrome.

Chrome | Safari
--- | ---
![image](https://github.com/techniq/svelte-ux/assets/177476/38f74d12-2729-416b-b2cb-d1358abf8a77) | ![image](https://github.com/techniq/svelte-ux/assets/177476/663b32af-9493-40fa-aa0a-1374a5167d1e)

I've had a note to [improve](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/TextField.svelte#L127-L150) this functionality.  Hopefully I (or someone else) can get to it soon.  The current workaround is not using `type="decimal"` and manually converting the value.

I do wonder if some of this handling is needed, or shouldn't be replaced with `e.target.valueAsNumber` (although Svelte already does this for `<input type="number" bind:value >`.

**Comment by dimfeld** [comment]
Hmm, this doesn't reproduce for me, using Safari 17.2.1. I just tried it with the sample decimal TextField in the docs site.

**Comment by dimfeld** [comment]
Posted this on the Discord, but here for the record. This appears to be a bug in Safari 17.1, fixed in 17.2
![image](https://github.com/techniq/svelte-ux/assets/1369558/4bea068e-4780-43c0-9a7a-f933b33dec29)

**Comment by techniq** [comment]
> not returning the correct value

You could say that :) 

![image](https://github.com/techniq/svelte-ux/assets/177476/91e2a63a-fcae-4346-92ab-1f45e7e49243)

**Comment by techniq** [comment]
@pekeler I'm going to close this as I don't see a way to workaround it otherwise, and at least it's resolved in the latest Safari release :)

**Comment by pekeler** [comment]
Makes sense. Thanks.

(Safari is my default browser. Quite interesting I never noticed this browser bug on any other site. I guess almost nobody is using real number inputs and does their own parsing.)

**Comment by 157Thor** [comment]
Can we reopen this? This issue is happening for me on chrome and brave
