### ISSUE TITLE
Handle svelte-check warnings

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#186]
- [x] Handle all `svelte-check` warnings (A11y, unused variables, etc) so the console is clean
  - Possibly leverage `<!-- svelte-ignore ... -->` **temporarily**
- [x] Setup CI to run `svelte-check` and fail build
- [ ] If `<!-- svelte-ignore ... -->` or `// @ts-expect-error` are used, properly handle remaining items
- [x] Rinse/repeat in [LayerChart](https://github.com/techniq/layerchart)
- [x] Enjoy a peaceful dev experience with improved accessibility

---

Reference
- `pnpm check --no-tsconfig --ignore "dist,src/routes`
- https://www.w3.org/WAI/ARIA/apg/patterns/
  - https://www.w3.org/WAI/ARIA/apg/example-index/
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA
- https://www.radix-ui.com/primitives/docs/overview/introduction
- https://react-spectrum.adobe.com/react-aria/Button.html
- https://melt-ui.com/docs/introduction

**Comment by jycouet** [comment]
in user land, if you add in `svelte.config.js` the function `onwarn`: 

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
	// ...

	onwarn(warning, defaultHandler) {
		// Do not show 3rd party warnings
		if (warning.filename.includes('node_modules')) return

		defaultHandler(warning)
	},

	// ...
}

export default config
```

I find it nice until it's "fixed" 😉

**Comment by techniq** [comment]
Making good progress in PR #409

**Comment by techniq** [comment]
![zoolander-will-ferrell](https://github.com/techniq/svelte-ux/assets/177476/fe51a2fa-4556-4397-a3fe-5c8ccc2a358d)

![image](https://github.com/techniq/svelte-ux/assets/177476/0d84af15-9128-43c5-af60-534480cd9309)

![image](https://github.com/techniq/svelte-ux/assets/177476/91953b8d-a613-41e7-962d-bc260433ac98)

**Comment by jycouet** [comment]
> ![zoolander-will-ferrell](https://private-user-images.githubusercontent.com/177476/342117068-fe51a2fa-4556-4397-a3fe-5c8ccc2a358d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE3MDY4LWZlNTFhMmZhLTQ1NTYtNDM5Ny1hM2ZlLTVjOGNjYzJhMzU4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQxNGZkMjJhYzRhNWExZjY1NjA2Njk4YmIzMTE1MDU1NmFhZmQyYjM5NDg3MTRmMjMzNzg4ZWNlNDEwODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KovKhKbGvvb8fAcddUgCIV37Vqe3CNOCnbYuq2LsXMU) [ ![zoolander-will-ferrell](https://private-user-images.githubusercontent.com/177476/342117068-fe51a2fa-4556-4397-a3fe-5c8ccc2a358d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE3MDY4LWZlNTFhMmZhLTQ1NTYtNDM5Ny1hM2ZlLTVjOGNjYzJhMzU4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQxNGZkMjJhYzRhNWExZjY1NjA2Njk4YmIzMTE1MDU1NmFhZmQyYjM5NDg3MTRmMjMzNzg4ZWNlNDEwODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KovKhKbGvvb8fAcddUgCIV37Vqe3CNOCnbYuq2LsXMU) ](https://private-user-images.githubusercontent.com/177476/342117068-fe51a2fa-4556-4397-a3fe-5c8ccc2a358d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE3MDY4LWZlNTFhMmZhLTQ1NTYtNDM5Ny1hM2ZlLTVjOGNjYzJhMzU4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQxNGZkMjJhYzRhNWExZjY1NjA2Njk4YmIzMTE1MDU1NmFhZmQyYjM5NDg3MTRmMjMzNzg4ZWNlNDEwODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KovKhKbGvvb8fAcddUgCIV37Vqe3CNOCnbYuq2LsXMU) [ ](https://private-user-images.githubusercontent.com/177476/342117068-fe51a2fa-4556-4397-a3fe-5c8ccc2a358d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE3MDY4LWZlNTFhMmZhLTQ1NTYtNDM5Ny1hM2ZlLTVjOGNjYzJhMzU4ZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQxNGZkMjJhYzRhNWExZjY1NjA2Njk4YmIzMTE1MDU1NmFhZmQyYjM5NDg3MTRmMjMzNzg4ZWNlNDEwODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KovKhKbGvvb8fAcddUgCIV37Vqe3CNOCnbYuq2LsXMU)
> 
> ![image](https://private-user-images.githubusercontent.com/177476/342116949-0d84af15-9128-43c5-af60-534480cd9309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE2OTQ5LTBkODRhZjE1LTkxMjgtNDNjNS1hZjYwLTUzNDQ4MGNkOTMwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTAyODM5NzFmYWQ5OWM4NDVhOGY0MDUxYWNiODIyZmFhNTRiMjUxNjQ4Zjg5YTYzODA1ZjYwZDE5ZDlkYzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rDp-x4XT-BTNA2IWiddYIz37RYb8GBcFLQv-YgRx0jU)
> 
> ![image](https://private-user-images.githubusercontent.com/177476/342116951-91953b8d-a613-41e7-962d-bc260433ac98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTA2MDUsIm5iZiI6MTcxOTIxMDMwNSwicGF0aCI6Ii8xNzc0NzYvMzQyMTE2OTUxLTkxOTUzYjhkLWE2MTMtNDFlNy05NjJkLWJjMjYwNDMzYWM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQwNjI1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzY4MGI4ZGQ3Yzc2NjFmY2IzOWZiNWFiOGI0ZjJhOWY4NjBjYTA0MDUzMjMxOGM5OGYxMGM2MGY0MTgxY2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4qFoB5jZoyYF5DEhrjSH2yMlpDnOKos4j6ie8sYpi9o)

That's AMAZING!!!!
Good job

**Comment by techniq** [comment]
Thanks @jycouet.  LayerChart is in progress as well
