### ISSUE TITLE
Refine package depencencies

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#200]
Need to think how this might impact LayerChart (if at all)

Update [Svelte UX](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/package.json)
- [x] Move `prism*` from peer to dev
- [x] Move `fortawesome/*` from peer to dev
- [x] Remove `sveld` from peer (already dev)
  - Should this be moved from `devDepencies` to `dependencies` due to the vite [plugin](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/plugins/vite.js#L1) which is used in [LayerChart](https://github.com/techniq/layerchart/blob/3dff9f1f2a5265b0b1a10215e171671de12187f7/packages/layerchart/vite.config.js#L2)?

Update [LayerChart](https://github.com/techniq/layerchart/blob/main/packages/layerchart/package.json)
- [x] Add `prismjs` and  `prism-svelte` as dev
- [ ] `sveld`? (see above)

**Comment by jycouet** [comment]
Actually, you already did it in `layerChart` 4 days ago: https://github.com/techniq/layerchart/blob/dd55df13282f33665f38a8cd1482678ec9b961b3/packages/layerchart/package.json#L53-L55

PR open for `svelte-ux` 👍

**Comment by techniq** [comment]
> Actually, you already did it in `layerChart` 4 days ago: https://github.com/techniq/layerchart/blob/dd55df13282f33665f38a8cd1482678ec9b961b3/packages/layerchart/package.json#L53-L55
> 
> PR open for `svelte-ux` 👍

Oh yeah, when I removed the `package-lock.json` file to [fix](https://github.com/techniq/layerchart/commit/cc30b6b12d5f229a43bc9f6185fae35be77f9f7a) the Cloudflare build, these kind of issues showed up :).  Thanks!

Once we finish PR's #191 and #192 and merge into `next` branch/PR, I publish a new `svelte-ux@next` release and update the LayerChart design tokens PR / next package and we can see if we need to do anything else.

**Comment by techniq** [comment]
done
