### ISSUE TITLE
Not loading styles

### ISSUE THREAD

**Issue by Ciamuthama** [techniq/svelte-ux#220]
Why is that if i follow the installation process and the configuration process the styles are not applied unless i place the 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```
 in my `styles.css` file but if i place it in the `layout.svelte` file like so

``` 
<style lang='postcss'>
	@tailwind base;
	@tailwind components;
	@tailwind utilities;
</style>
```
 the styles are applied is this issue on my side or?

**Comment by techniq** [comment]
Hi @Ciamuthama 👋.  I'm not certain what the issue can be, but I've used both approaches.

The docs currently use [sveltePreproces](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/svelte.config.js#L2) and `<style lang='postcss'>` in [+layout.svelte](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/routes/%2Blayout.svelte#L158-L161).

The `npx create-svelte-ux@latest` templates, such as [starter](https://github.com/techniq/svelte-ux/tree/main/packages/create-svelte-ux/templates/starter), use [vitePreprocess](https://github.com/techniq/svelte-ux/blob/main/packages/create-svelte-ux/templates/starter/svelte.config.js#L2) and [app.postcss](https://github.com/techniq/svelte-ux/blob/main/packages/create-svelte-ux/templates/starter/src/app.postcss).  The Tailwind SvelteKit [guide](https://tailwindcss.com/docs/guides/sveltekit) also uses this process as well (but names their file `app.css`).

I would take a look at your `svelte.config.js` and `postcss.config.cjs` and compare to the docs setup or the template and see if there is a difference.  If you want to share a repo / stackblitz link, I could take a look.

**Comment by Ciamuthama** [comment]
Hello @techniq here are the links to my postcss and svelte config files https://github.com/Ciamuthama/anonjot-svelte-v/blob/master/postcss.config.cjs

https://github.com/Ciamuthama/anonjot-svelte-v/blob/master/svelte.config.js

**Comment by techniq** [comment]
@Ciamuthama Hmm... I haven't tried using `vitePreprocess` with `<style>`.  I've done `sveltePreprocess` with `<style>` and `vitePreprocess` with a separate `app.css`.

I know the kit [docs](https://kit.svelte.dev/docs/integrations#preprocessors-vitepreprocess) say `vitePreprocess` do not support all the use cases of `sveltePreprocess`, but I think it's mostly things like CoffeeScript and not postcss related.  Also, when I look at the `vite-plugin-svelte` [docs](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/preprocess.md), it says...

> By default, PostCSS or LightningCSS ([if configured in Vite](https://vitejs.dev/config/shared-options.html#css-transformer)) is applied to all <style> tags.

With that said, I had trouble moving Svelte UX's docs to `vitePreprocess`, but it very much could be related to this (and just needing to move these declarations to a separate `app.css` file.

Unless you're adverse to it, I think sticking with the separate `app.css` is probably best, but you could also try `sveltePreprocess`.  When I get a moment to try `viteProprocess` with the docs again, I'll try to see if `app.css` is the fix, and probably just embrace it.

Svelte UX does use some `@apply` in a few comments, so hopefully that still works, it might just be the `@tailwind ...` plugin.

**Comment by Ciamuthama** [comment]
Thank you @techniq, since `svelte-ux` is working with `app.css` I will stick with that for now, thank you again for taking your time to respond to my issue. 🙏

**Comment by techniq** [comment]
Very welcome.

Btw, I just switched the docs to use `vitePreprocess` (see [commit](https://github.com/techniq/svelte-ux/commit/f58a43d20bbb98dc7d94d798ff54b5908ba8f9cc)) and it required using a separate `.css` file just for the `@tailwind` (`@apply` and everything else looks to work without issue).

Been on my list of things to do, and felt like no time like the present (closed an old issue and removed an extra dependency, which is always a win).

I'm going to close this issue for now, but if I find a way to handle `@tailwind` within `+layout.svelte`, I'll be sure to post here.

**Comment by dimfeld** [comment]
Yeah, I don't think there's any other solution here.

Putting the `@tailwind` tags inside `<style>` in your `+layout.svelte` file, the styles end up scoped to just that one file, just like any other CSS that you might put in a Svelte file.

With sveltePreprocess you could write `<style global>`, which would mark all the styles in that tag as global, but vitePreprocess doesn't support that so putting it in a separate CSS file is the right way here.

**Comment by techniq** [comment]
Thanks @dimfeld.  Surprisingly I didn't have to use `<style global>` or `<style>:global(...) { ... }</style>` when [using](https://github.com/techniq/svelte-ux/blob/cf28c51abb44fe82b83a1cf9f8ee66f2bcfe3b74/packages/svelte-ux/src/routes/%2Blayout.svelte#L292-L295) `sveltePreprocess`.  Adding a separate `app.css` isn't a big deal and I've been wanting to get away from `sveltePreprocess` (#57)
