### ISSUE TITLE
next branch: ThemeSwitch FOUC with SSR

### ISSUE THREAD

**Issue by dimfeld** [techniq/svelte-ux#227]
ThemeSwitch shows the light mode setting then moves over to dark mode if loading in SSR. This is because the positioning is just using the checked state instead of being keyed on the `dark` class.

This is a GIF of me refreshing the page three times.

![CleanShot 2024-02-02 at 21 07 12](https://github.com/techniq/svelte-ux/assets/1369558/6ae6b568-ffc1-4b9d-853a-f4d8a891701a)

This can probably just be overridden by passing in some custom classes to disable the normal positioning classes and use `dark:` variant based code instead. I'll make a PR for this soon-ish.

**Comment by techniq** [comment]
Fixed via #228
