### ISSUE TITLE
Circular Dependencies causing nothing to render

### ISSUE THREAD

**Issue by Cheesy-Brik** [techniq/svelte-ux#247]
```(!) Circular dependencies
node_modules/d3-interpolate/src/value.js -> node_modules/d3-interpolate/src/array.js -> node_modules/d3-interpolate/src/value.js
node_modules/d3-interpolate/src/value.js -> node_modules/d3-interpolate/src/object.js -> node_modules/d3-interpolate/src/value.js
node_modules/svelte-ux/dist/components/index.js -> node_modules/svelte-ux/dist/components/NumberStepper.svelte -> node_modules/svelte-ux/dist/components/index.js
```
I am getting this error when importing the ListItem component and it causes nothing to render onto the screen. Is there a fix for this?

**Comment by techniq** [comment]
NumberStepper (and others in Svelte UX) should be handled by https://github.com/techniq/svelte-ux/commit/c1f43800449ff744db26ac38b7c9f95e3e5ea6ac (coming in next release).  Not sure why no one else is having this issue though (especially the docs) so could be something else.

**Comment by techniq** [comment]
Along with the circular reference, I took a look at the repo and it was a non-SvelteKit project based on [svelte-tailwindcss-template](https://github.com/sarioglu/svelte-tailwindcss-template).  Decided to switch to a SvelteKit project with static builds.
