### ISSUE TITLE
Support `NodeNext` packages

### ISSUE THREAD

**Issue by huntabyte** [techniq/svelte-ux#280]
Projects and packages using `"moduleResolution": "NodeNext"` are unable to use `svelte-ux` or `layerchart` due to these projects not importing with the `.js` extension. The simplest way to resolve this is to set the projects `"moduleResolution": "NodeNext"` and fix the imports to prevent regression.

References:
	- https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries
	- https://kit.svelte.dev/docs/packaging#caveats

**Comment by techniq** [comment]
Thanks for the heads up (and docs) @huntabyte.

I'll switch both projects over to `"module": "NodeNext"` / `"moduleResolution": "NodeNext"` in the next few days.  Quick check on Svelte UX looks like it might take a hot minute 😓 (and haven't looked at LayerCake yet).

![image](https://github.com/techniq/svelte-ux/assets/177476/d7bb695d-8a01-4b1f-9c5e-c75e5066a9aa)

Quick scan of the docs it doesn't look like this should be a breaking change, right?

**Comment by techniq** [comment]
Take one down... pass it around... 

![image](https://github.com/techniq/svelte-ux/assets/177476/1df2291c-03da-4f80-bae0-48855b8969ee)

Still have 4 errors in 1 file I'm not 100% sure how to solve yet...

![image](https://github.com/techniq/svelte-ux/assets/177476/ceeb6d8d-842b-4550-91f7-ca2ec7271316)

![image](https://github.com/techniq/svelte-ux/assets/177476/3a8ef373-f21e-4511-b5e0-e95b1534696d)

Going to step away for a while and hopefully the solution presents itself :)

**Comment by huntabyte** [comment]
> Quick scan of the docs it doesn't look like this should be a breaking change, right?

Nope, this shouldn't be a breaking change! Projects not using `NodeNext` will work just as before! It just opens up those using `NodeNext` to be able to use it!

**Comment by techniq** [comment]
@huntabyte Both Svelte UX (`0.61.1`) and LayerChart (`0.32.0`) have been updated to support `NodeNext` packages.  Let me know if you come across any issues.
