### ISSUE TITLE
Fix `npm create svelte-ux@latest` on Windows

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#288]
Looks to be an issue handling Window paths...

![image](https://github.com/techniq/svelte-ux/assets/177476/ed5e93fb-1995-4c37-a859-5dae06afb5cf)

tested works on Mac

![image](https://github.com/techniq/svelte-ux/assets/177476/7e87455a-a908-4c6f-9487-38c5d4acd990)

See [discussion](https://discord.com/channels/920755200552226868/1216683467127914528)

**Comment by techniq** [comment]
@jycouet thoughts?

**Comment by jycouet** [comment]
I have to look somewhere else, I think I fixed it already 🤔
RN I can't really look, I'll do in a few days.

_Ping me again if I forget._

**Comment by techniq** [comment]
No rush.  Thanks @jycouet

**Comment by Carsten-R** [comment]
Still the same issue with version 0.3.3 on windows

**Comment by jycouet** [comment]
Actually, I didn't managed it... I just did this in another package: 
https://github.com/jycouet/kitql/blob/main/packages/create-kitql/bin.js#L195-L201

Here is the same function in `svelte-ux`: https://github.com/techniq/svelte-ux/blob/main/packages/create-svelte-ux/bin.js#L191-L193

I'm sure it's possible to have this working in all OS... But would be easier to have a windows to try things out.
Someone wanna give a shoot? _(Or should I boot my windows? ^^)_

**Comment by 29th-Day** [comment]
I wrote a fix #353 for windows but I currently cannot test it other OSs

**Comment by techniq** [comment]
Tested on Mac.  Thanks @29th-Day!

![image](https://github.com/techniq/svelte-ux/assets/177476/8ba95771-3917-4cfa-adbb-884cf4438871)

**Comment by techniq** [comment]
Just waiting on CI to catch up on the queue, then will publish as `0.4.0` (still use `npm create svelte-ux@latest`)

**Comment by techniq** [comment]
Done.  Thanks again @29th-Day (Gerald)

**Comment by jycouet** [comment]
Nice, thx a lot 👍
