### ISSUE TITLE
Cannot use key events with Dialog

### ISSUE THREAD

**Issue by erlenddahl** [techniq/svelte-ux#299]
The stopPropagation on line 98 in [Dialog.svelte](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Dialog.svelte) prevents us from using key events when a Dialog is open.

```
on:keydown={(e) => {
      // Do not allow event to reach Popover's on:keydown
      e.stopPropagation();
```

I have an info Dialog where I would like to use the arrow keys to open the next info item, but because of this line, that event never reaches my component.

It looks like you only want to prevent the Escape button, so perhaps a solution would be to move the e.stopPropagation inside the if(e.key==="Escape") check, like this:

```
on:keydown={(e) => {
      // Do not allow event to reach Popover's on:keydown
      if (e.key === 'Escape') {
        e.stopPropagation();
        if (!persistent) {
          open = false;
        }

        dispatch('close-attempt');
      }
    }}
```

I'm not using mouseup, but I assume the e.stopPropagation in on:mouseup can cause similar issues, but that may be harder to fix.

**Comment by techniq** [comment]
Good catch.  `e.stopPropagation()` used to only be called for `e.key === 'Escape'` but was [changed](https://github.com/techniq/svelte-ux/commit/951d2cd30f5f7fca410a2ff54c74007d02490e77) a while ago, but I think the main reason was the check used to also include `&& !persistent` which it no longer [does](https://github.com/techniq/svelte-ux/commit/9e047326950a44a6cce36bf6da399a2e36641324).  Also, this is how [Popover](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Popover.svelte#L55-L58) current works.  Making the change for the next release.
