### ISSUE TITLE
Theme Page breaks when changing a color on a Skeleton Theme

### ISSUE THREAD

**Issue by dimfeld** [techniq/svelte-ux#314]
To reproduce:

1. go to https://svelte-ux.techniq.dev/theme
2. Choose any theme from Skeleton
3. Open the color picker on any of the colors
4. Change the color

You get an error about calling Object.entries on an undefined value.

**Comment by techniq** [comment]
@dimfeld Thanks, taking a look

**Comment by dimfeld** [comment]
flattenThemeColors recursive logic doesn't handle `undefined` values properly, can fix in a bit if you dont get it first

**Comment by dimfeld** [comment]
never mind, just saw your commit :)
