### ISSUE TITLE
Some way to copy themes to clipboard with only the explicitly set variables.

### ISSUE THREAD

**Issue by dimfeld** [techniq/svelte-ux#318]
If you copy a theme to the clipboard, it copies all the variables, including all the ones that the plugin calculates for you. I think it would be potentially more useful to only copy the explicitly configured values out.

The primary benefit is that it becomes easier to tweak the generated theme posthoc and have the plugin then propagate the changes to all the other shades. Right now you can do that by deleting a bunch of the generated theme variables from the tailwind config but it's not clear right away which ones should be removed.

**Comment by techniq** [comment]
agreed :)
