### ISSUE TITLE
In a Form, the SelectField Seems to return the Label, not the Value

### ISSUE THREAD

**Issue by CropWatchDevelopment** [techniq/svelte-ux#336]
I am using a selectfield like so:
<SelectField
				label="Role"
				name="permission_level"
				options={[
					{ value: '1', label: 'Admin (view, Edit, Update, Delete)' },
					{ value: '2', label: 'User (view data, Download Data' },
					{ value: '3', label: 'Viewer (view data only)' }
				]}
			/>
			
When calling
const formData = await request.formData();
let result = formData.get('permission_level')
I would hope to get the value, meaning 1 or 2 or 3, however I get the label, in the case of 3, i would get the value 'Viewer (view data only)' in the result variable.

Is this known yet?

**Comment by techniq** [comment]
@CropWatchDevelopment Great feedback.  Most of my apps do not leverage normal form submission so never encountered this.  Should be fixed via https://github.com/techniq/svelte-ux/pull/337

**Comment by CropWatchDevelopment** [comment]
Sounds great techniq! Looking forward to it, Until then, If anyone is interested, here is my workaround:

<input type="hidden" name="permission_level" value={permission_level} />
			<SelectField
				label="Role"
				id="permission_level"
				bind:value={permission_level}
				options={[
					{ value: '1', label: 'Admin (view, Edit, Update, Delete)' },
					{ value: '2', label: 'User (view data, Download Data' },
					{ value: '3', label: 'Viewer (view data only)' }
				]}
			/>

**Comment by techniq** [comment]
Btw, the root issue with `name` was passed to `TextField` and thus used it's `value`, which was the selected options label.  Added a hidden input to set `name` and the current `value`.

**Comment by techniq** [comment]
Basically doing the same thing :).  Pushing a release now

**Comment by techniq** [comment]
`0.62.11` released.  Thanks for the report
