### ISSUE TITLE
DatePicker: Month / Year Selection

### ISSUE THREAD

**Issue by abdullahcalisir12** [techniq/svelte-ux#366]
Use case: To ask users about their birthdays, there is no easy way to navigate between years and months.

Possible solutions: 
1. There are already some components we can use (MonthList and YearList). When the user clicks year at the top, the Year List selection will appear after clicking a year. Month List selection will appear and then click a month, and days in the selected year, and the selected month will be available for the user to pick.
2. A simple dropdown button for month and year selection at the top of the picker.

**Comment by techniq** [comment]
Resolved via https://github.com/techniq/svelte-ux/commit/6546b50692268d4fea5b0d0a0b6991c26806aa68

https://github.com/techniq/svelte-ux/assets/177476/d91acd69-3f08-444f-8971-0b7dcfacf2a4
