### ISSUE TITLE
Vite Plugin Svelte: Many Warnings: Self Closing HTML tags, non-interactive elements should not be assigned mouse or keyboard event listeners).

### ISSUE THREAD

**Issue by arkmech** [techniq/svelte-ux#387]
https://github.com/sveltejs/svelte/issues/1105

Using `vite-plugin-svelte` and on `vite dev` getting many warnings from this package.

1. Self-closing HTML tags for non-void elements are ambiguous — use `<div ...></div>` rather than `<div ... />`
2. Non-interactive element `<menu>` should not be assigned mouse or keyboard event listeners.

Way too many warnings to post all of them, but they fit into these two categories. #1 is easy to fix.

Can all these issues be resolved?

```ts
"svelte-ux": "^0.62.8"
```

**Comment by techniq** [comment]
Hey @arkmech 👋, thanks for checking out Svelte UX.  Yeah, there are currently a good number of warnings in the library that need addressed.  I'm hoping to dedicate some time to this, but I just lack a lot of extra bandwidth at the moment.  This is currently being tracked by https://github.com/techniq/svelte-ux/issues/186.
