### ISSUE TITLE
`AppLayout`/`AppBar` without drawer

### ISSUE THREAD

**Issue by plutonium-239** [techniq/svelte-ux#418]
Is there a way to make the `AppBar` without the aside/drawer of `AppLayour`? 

I've tried various methods including setting CSS display (in that case the problem is that the `--drawerWidth` variable still makes space for the drawer as if it were open), and only using `AppBar` without `AppLayout` - but then the spacing gets messed up.

If not, I would propose either making the `AppBar` being valid as an independent element without `AppLayout`, or adding an option in `AppLayout` which lets us choose whether we want the drawer or not (which is probably easier to implement).

**Comment by plutonium-239** [comment]
As I learned from #279, it can also be done using the `showDrawer` store

**Comment by techniq** [comment]
Awe, interesting, so you want to fully remove the drawer (not just initialize it closed).  I could see adding `<AppLayout disableDrawer>` or possibly something in `settings()` to make it coordinate with `AppBar` a little easier.

I assume you're going for the typical home page layout with no sidebar, such as
- https://d3js.org/
- https://ui.shadcn.com/
- https://melt-ui.com/
- etc
