### ISSUE TITLE
TextField action autosize does not work with bind

### ISSUE THREAD

**Issue by michalss** [techniq/svelte-ux#422]
Hi
autosize does not work with bind:value. Can you please help me out how to make TextField autosize when i do bind value ?

```svelte
<TextField
  label="Text Translated"
  multiline
  name="textTranslated"
  bind:value={selectedItem.text_translated}
     actions={(node) => {
    // @ts-expect-error
    return [autoHeight(node)];
  }}
 />
```

**Comment by techniq** [comment]
Hey @michalss 👋

I just tested and couldn't reproduce the `bind:value` issue you are experiencing, and updated the autoheight [example](https://svelte-ux.techniq.dev/docs/components/TextField#multiline_with_autoheight).

To set a static height, you can pass classes to the underlying `input`, such as:

```svelte
<TextField multiline classes={{ input: 'h-[100px]' }} />
```

I've also added this as an [example](https://svelte-ux.techniq.dev/docs/components/TextField#multiline_with_fixed_height).
