### ISSUE TITLE
Improve clicking outside of fields (MenuField, MultiSelectField, etc) when on Dialog/Drawer 

### ISSUE THREAD

**Issue by techniq** [techniq/svelte-ux#444]
See example using `MenuField` within `Drawer`

https://github.com/user-attachments/assets/04ab1f34-f54e-4359-83de-f2044c95ac71

See also [discussion](https://discord.com/channels/920755200552226868/1266621149442211922) regarding `MultiSelectField` with `Dialog`

Likely the culprit is the [event.stopPropagation()](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/Drawer.svelte#L97-L100) but there is also some [coordination](https://github.com/techniq/svelte-ux/commit/951d2cd30f5f7fca410a2ff54c74007d02490e77) with `Popover` to not break when doing so.

**Comment by sergejbog** [comment]
Any news about this?

**Comment by techniq** [comment]
> Any news about this? I want to hide a popover when someone clicks outside, but it doesn't seem to work inside a Drawer.

@sergejbog News flash: This just in... fixed in [0.75.3](https://github.com/techniq/svelte-ux/releases/tag/svelte-ux%400.75.3) via #499.

I originally had stopped event propagation to handle some unexpected triggering of nested models (Menu/Dialog/Drawer, etc), but I could not identify any reasons to keep these in the current state.

Please let me know if you spot any regressions, but I did a fair bit of manual validation and couldn't identify anything, and fixes the Menu click outside [use case](https://svelte-ux.techniq.dev/docs/components/Drawer#menufield_within_drawer)

https://github.com/user-attachments/assets/acf469fd-96de-4141-93af-3c94e544fb30
