### ISSUE TITLE
Confusing //console.log comments in code base

### ISSUE THREAD

**Issue by baterson** [techniq/svelte-ux#450]
Hello @techniq I've been exploring the code base and find some debug comments like this:

// console.log('clicked:menuItems', e.target, menuEl);
https://github.com/techniq/svelte-ux/blob/f419435edbf4f0c004896e87e92b9f7ba770bcc9/packages/svelte-ux/src/lib/components/Menu.svelte#L51

If someone just forgot to remove it, I would be happy to contribute to remove similar comments :)

**Comment by techniq** [comment]
Hey @baterson 👋.  There is definitely some cleanup that can be done with `console.log`.

One thing I plan to do is leverage [Logger](https://svelte-ux.techniq.dev/docs/utils/Logger) which lets you opt into these messages by component/level at runtime via `localStorage.logger = '...'`.  I think I left many of these as breadcrumbs to add (see [issue](https://github.com/techniq/svelte-ux/issues/43)).  If you would want to start that process of using `Logger` that would be awesome!  

Using [SelectField](https://github.com/techniq/svelte-ux/blob/main/packages/svelte-ux/src/lib/components/SelectField.svelte#L28) as a reference should help, but you basically just create an instance for the component...

```js
const logger = new Logger('Menu');
```
then replace `console.log()` with `logger.debug()`, `logger.info()`, `logger.error()`, etc.

**Comment by techniq** [comment]
Closed via https://github.com/techniq/svelte-ux/pull/452
