### ISSUE TITLE
cannot click the text part of an option in SelectField with an option slot

### ISSUE THREAD

**Issue by Ennoriel** [techniq/svelte-ux#510]
On the [SelectField documentation page](https://svelte-ux.techniq.dev/docs/components/SelectField#option_slot), the first example with an option slot isn't working properly when clicking on the **text part** of an option.

I've been diging a bit on why, the div seems to be the culprit but I don't understand why. There's no `pointer-events: none` css attribute that would explain the behavior.

**Comment by techniq** [comment]
I have a [PR](https://github.com/techniq/svelte-ux/pull/512) fix but need to vet it a little more before merging.
