### ISSUE TITLE
The "links" of the Related section of each documentation page should be anchor elements

### ISSUE THREAD

**Issue by Ennoriel** [techniq/svelte-ux#511]
The Related section of each documentation page is a great way to navigate quickly through the documentation. However, the items are not clickable buttons or anchors, which prevents using the keyboard to select them and prevents right-clicking to open them in a new tab.

**Comment by techniq** [comment]
Great callout, thanks @Ennoriel.  [Fixed](https://github.com/techniq/svelte-ux/commit/df4e367ac85bb17202ca025d3bee3da16f2058b2) on Svelte UX and LayerChart docs
