### ISSUE TITLE
Selection to have an `on:change` event

### ISSUE THREAD

**Issue by sazzad-sat** [techniq/svelte-ux#520]
Currently there are no way to bind to `let:selected` data because of svelte's slot props limitations. A reasonable option can be including an event such as `on:change` to use it outside of the scope of `Selection` component.

```svelte
<script>
  import { Selection } from "svelte-ux";

  let selectedOptions = []
</script>

<Selection
  let:selected
  on:change={(e: any) => {
    selectedOptions = e
  }}
>
  ...
</Selection>

{selectedOptions.length} // accessible outside
```

**Comment by techniq** [comment]
@sazzad-sat good feedback.  Added in [0.76.0]()

Note: [Selection](https://svelte-ux.techniq.dev/docs/components/Selection) is a lightweight state component wrapper around [selectionStore](https://svelte-ux.techniq.dev/docs/stores/selectionStore) and you can use the store directly if you need more imperative control.

Svelte UX will [soon](https://github.com/techniq/svelte-ux/pull/489) use `@layerstack/*` packages so you can also use `import { selectionStore } from '@layerstack/svelte-stores'` - https://www.layerstack.dev/docs/svelte-stores/selectionStore
